name: my_cv
version: 1.0.0+1
publish_to: 'none'
description: A little project for my personal CV.

environment:
  sdk: ^2.17.0

dependencies:
  archive: ^4.0.9
  flutter:
    sdk: flutter
  re_editor: ^0.10.0
  url_launcher: ^6.3.2

dev_dependencies:
  icon_font_generator: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/BciFortlevDriverApp/archive.zip
    - assets/SapIntegrationSuiteLearningJourney/ApimProxy/archive.zip
    - assets/SapIntegrationSuiteLearningJourney/IFlowProxy/archive.zip
    - assets/SapIntegrationSuiteLearningJourney/ExceptionHandler/archive.zip
    - assets/SapIntegrationSuiteLearningJourney/OAuth2TokensHandler/archive.zip
    - assets/SapIntegrationSuiteLearningJourney/GoogleFirebaseAuthUsers/archive.zip
    - assets/SapIntegrationSuiteLearningJourney/InterStatementOAuth2Mtls/archive.zip
    - assets/SapIntegrationSuiteLearningJourney/Calculator/archive.zip
    - assets/SapIntegrationSuiteLearningJourney/ConversionsAndFtp/archive.zip
    - assets/SapIntegrationSuiteLearningJourney/SqlServerWithXslt/archive.zip
    - assets/Startup/
  fonts:
    - family: Icons
      fonts:
        - asset: assets/icons/icons.otf